### ISSUE TITLE
Small Error in Notebook 5

### ISSUE THREAD

**Issue by CobeA527** [pupil-labs/pupil-tutorials#15]
Hi everyone, 

I think there is a small error in a jupyter notebook https://github.com/pupil-labs/pupil-tutorials/blob/master/05_visualize_gaze_velocity.ipynb: 

in In[4] instead of 
`exported_gaze[["gaze_point_3d_z"]] = negative_z_values * -1`
it should be 
`exported_gaze[negative_z_mask][["gaze_point_3d_z"]] = negative_z_values * -1`

**Comment by papr** [comment]
Hi, good catch!
If I am not mistaken though, the proposed solution will not work as expected because you are modifying a copy instead of a view of the data. You can read more about this [here](https://realpython.com/pandas-settingwithcopywarning/).

I created a [small example](https://gist.github.com/papr/ea91e299c7536f71cb45f55a65ffe64f) that shows the issue with the original implementation, your proposed solution, as well as a version of my own.

@CobeA527 could you take the example to fix the notebook and create a pull request with the changes? Your contribution would be much appreciated! 🙏🏻

**Comment by CobeA527** [comment]
Ah nice, 

good to know! Thank you @papr  :) I created a pull request.:)

**Comment by papr** [comment]
Fixed in https://github.com/pupil-labs/pupil-tutorials/pull/16
